### ISSUE TITLE
AttributeError: 'NFNet' object has no attribute 'variant'

### ISSUE THREAD

**Issue by pervin0527** [ypeleg/nfnets-keras#1]
Hi. I try to use nfnets, but I get the following error.

### Error

    AttributeError: 'NFNet' object has no attribute 'variant'

### environment
- Ubuntu : 18.04
- Tensorflow : version 2.3 and 2.4 both give the same error.
- Keras : 2.4.3
- NFNets : 0.0.2

### code

    from nfnets_keras import NFNetF3, SGD_AGC
    
    model = NFNetF3(include_top=True, num_classes=10)
    model.compile( SGD_AGC(lr=1e-3), loss='categorical_crossentropy' )
    model.summary()    

How can i solve this Error?

**Comment by hoangthang1607** [comment]
Hello. I think this code is copied from my own ([link repo here](https://github.com/hoangthang1607/nfnets-Tensorflow-2)) and the code built on pytorch [here](https://github.com/vballoli/nfnets-pytorch/blob/main/nfnets/sgd_agc.py). I'm sure that the module `SGD_AGC` cannot work. In addition, I realized that I made a mistake in my code and he copied exactly the same mistake.

**Comment by wajahat-iqbal** [comment]
I am facing the same issue unable to run any of these ,Any solutions

**Comment by mithils3** [comment]
Same issue

**Comment by prateekkrjain** [comment]
I am getting the same error!!

**Comment by mohneesh7** [comment]
Getting the same error.
TF 2.3 and TF2.4
cuDNN 8.0

**Comment by prateekkrjain** [comment]
I was able to solve this error - It was just because 'variant' was being used before the assignment. Here is the fixed repo. https://github.com/prateekkrjain/nfnets-keras

But, there are more issues.

**Comment by pervin0527** [comment]
@prateekkrjain
I went into the link you gave me and installed it.
Installing with pypi causes the same issue. 
So, I tried using git clone, but there still seem to be a lot of other problems. I should just wait and use nfnets when it stabilizes.

**Comment by hoangthang1607** [comment]
You should see my implementation [here](https://github.com/hoangthang1607/nfnets-Tensorflow-2)

**Comment by joonjeon** [comment]
Same issue here..
