### ISSUE TITLE
tensorflow 2.4

### ISSUE THREAD

**Issue by jackyesf** [ypeleg/nfnets-keras#7]
not working on tensorflow 2.4

**Comment by Sicily-F** [comment]
hi, have you managed to get it to work yet? i'm interested in trying this net out!

**Comment by jackyesf** [comment]
It's working now,but i change a lot and replace sgd-agc by tfa.optimizers.SGDW.

**Comment by Sicily-F** [comment]
do you mind me asking if you used flow from directory or flow from dataframe? Would you be able to share your workflow? I'd ideally like to use Adam as an optimiser as I'd like to ensemble models and train on my own data, rather than imagenet

**Comment by jackyesf** [comment]
used a data generator from the original data.

**Comment by Sicily-F** [comment]
I tried using this image datageneraotr: from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, load_img ; but it doesn't seem to work with my version of tensorflow; any tips? I'm also using tensorflow 2.4.0

![image](https://user-images.githubusercontent.com/68450039/115158506-6249d600-a086-11eb-8934-42a0f5a03f3c.png)

**Comment by Sicily-F** [comment]
> used a data generator from the original data.

hi there,

Did you get this to work? I read that other people were having a problem with this implementation, largely because it was a Pytorch one for example. I'm looking to try and run a single model in isolation, and then to ensemble it. Any suggestions would be amazing!
